### PR TITLE
Use valid JSON in german translation

### PR DESCRIPTION
**Pull request by ThorbenG**

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for spotting that!

**Comment by webmaster128** [comment]
Is this fix released somewhere? If I did not miss anything, the latest release is still broken: https://cdn.datatables.net/plug-ins/1.10.16/i18n/German.json

**Comment by ThorbenG** [comment]
@webmaster128 No release since 2017-08-31. He "haven't had the time to do it yet." https://github.com/DataTables/Plugins/issues/353

**Comment by webmaster128** [comment]
Thanks.

I ended up copying the translations I need into my project [as a language option](https://datatables.net/examples/basic_init/language.html), which saves me an extra AJAX call and avoids upgrading jquery from slim to full.

**Pull request merged**
