### PR TITLE
Resize on layout changes due to width changes

### PR DESCRIPTION
**Pull request by JMolenkamp**
Currently, resizing only happens based on height changes. However, the layout of surrounding elements may change due to width changes, which also requires resizing:

image

image

### CODE REVIEW

**Comment by AllanJard** [comment]
Just to confirm my understanding here - are you saying that when you resize horizontally the height of the rows will change? I can see how that would effect the number of rows that should be displayed, but that isn't shown in your screenshots, so I'm wondering if I've got the wrong end of the stick.

**Comment by JMolenkamp** [comment]
No, what i meant is that due to width changes, the layout of surrounding elements might change, which in turn changes the available height for the rows. In the second screenshot, the layout for the info and pagination elements has changed, which leaves less space for the rows. Currently, the plugin only acts based on height changes, but in this case it requires acting based on width changes to keep the entire table in view.

**Comment by AllanJard** [comment]
I'm with you now - thanks! It looks like there might be conflicts with your other change. Might you be able to rebase and update to get a clean merge?

**Comment by JMolenkamp** [comment]
Yeah, sure. I will be on vacation the coming week, after that i will fix the PR.

**Comment by JMolenkamp** [comment]
The PR has been updated

**Comment by AllanJard** [comment]
Super - many thanks!

**Pull request merged**
