### PR TITLE
Pagination Input plugin improvements.

### PR DESCRIPTION
**Pull request by GDoronin**
Hello Allan,

First of all - Thanks for such useful plugin! :)

Here is the story...

I found a bug, when restoring the state in the middle of pages (for example choose 5th page, then CTRL+F5) - I had disabled first/prev buttons.
Decided to fix it fastly.
Then I realized there are some things to improve, so I did some efforts to do these improvements.

I hope it's all right I made so many changes..

I reviewed previous project commits and noticed - there were many bugs caused by IF-ELSE statements (4fd76ca82c5e9f8cffee6796b17258a4254d0d5b, 03939698858aa977633b15e309eec6ce64e99027 etc) when navigating first/prev/next/last and disabling the buttons.
Please review my code and say what you think. The idea is to not react for each click event, but react once on-update, calculating the disable state once for all buttons and applying. And do not have all these many IFs. See previous code examples below:

```javascript
if (iCurrentPage == 2)
{
	$(nFirst).addClass('disabled');
	$(nPrevious).addClass('disabled');
}
$(nNext).removeClass('disabled');
$(nLast).removeClass('disabled');
```

or even THIS

```javascript
if (iNewStart === 0)
{
	$(nFirst).addClass('disabled');
	$(nPrevious).addClass('disabled');
	$(nNext).removeClass('disabled');
	$(nLast).removeClass('disabled');
}
else if (iNewStart == ((Math.ceil((oSettings.fnRecordsDisplay() - 1) / oSettings._iDisplayLength) - 1) * oSettings._iDisplayLength))
{
	$(nNext).addClass('disabled');
	$(nLast).addClass('disabled');
	$(nFirst).removeClass('disabled');
	$(nPrevious).removeClass('disabled');
}
else
{
	$(nFirst).removeClass('disabled');
	$(nPrevious).removeClass('disabled');
	$(nNext).removeClass('disabled');
	$(nLast).removeClass('disabled');
}
```

Now it is

```javascript
function calcDisableClasses(oSettings) {
	var start = oSettings._iDisplayStart;
	var length = oSettings._iDisplayLength;
	var visibleRecords = oSettings.fnRecordsDisplay();
	var all = length === -1;

	// Gordey Doronin: Re-used this code from main jQuery.dataTables source code. To be consistent.
	var page = all ? 0 : Math.ceil(start / length);
	var pages = all ? 1 : Math.ceil(visibleRecords / length);

	var disableFirstPrevClass = (page > 0 ? '' : oSettings.oClasses.sPageButtonDisabled);
	var disableNextLastClass = (page < pages - 1 ? '' : oSettings.oClasses.sPageButtonDisabled);

	return {
		'first': disableFirstPrevClass,
		'previous': disableFirstPrevClass,
		'next': disableNextLastClass,
		'last': disableNextLastClass
	};
}
```

And applying once:

```javascript
// Enable/Disable `first` button.
$(an).children('.' + firstClassName)
	.removeClass(oSettings.oClasses.sPageButtonDisabled)
	.addClass(disableClasses[firstClassName]);

// Enable/Disable `prev` button.
$(an).children('.' + previousClassName)
	.removeClass(oSettings.oClasses.sPageButtonDisabled)
	.addClass(disableClasses[previousClassName]);

// Enable/Disable `next` button.
$(an).children('.' + nextClassName)
	.removeClass(oSettings.oClasses.sPageButtonDisabled)
	.addClass(disableClasses[nextClassName]);

// Enable/Disable `last` button.
$(an).children('.' + lastClassName)
	.removeClass(oSettings.oClasses.sPageButtonDisabled)
	.addClass(disableClasses[lastClassName]);
```

And the short list of changes:

- Reusable functions calcDisableClasses/calcCurrentPage/calcPages - less duplicated code means less errors.
- Reused code for calculating `disabled` classes from main jQuery.dataTables source code to be consistent.
- Moved duplicated strings to constant variables.
- Reworked approach with buttons disabling.
- Totally removed all if-else branches for buttons disabling. Less conditional branching means less errors again :).
- Fixed bug when restoring state in the middle of pages had disabled first/prev buttons.
- It seems it's not required to assign disabled classes to buttons on init, cause they will be assigned on update anyway.
- Reworked on-update loop over each instance of the pager to jQuery.children selector, which already executes for each matched descendant.
- Wrapped all plugin code to IIFE pattern to have private static functions easily, and not expose them to global scope.

### CODE REVIEW

**Comment by DataTables** [comment]
Awesome! Are you happy for this to be released under the MIT license?

**Comment by GDoronin** [comment]
Sure I am.

BTW About #219 - It works for two paginators as well :)

**Comment by DataTables** [comment]
Absolutely brilliant!

Two update requests:

1. Could you add a semi colon at the very end (`...(jQuery);`) so it will pass linters which check for it
2. Put your own name as the author! Leave mine if you want, but this is your work :-)

**Comment by GDoronin** [comment]
Thanks for the kind words, I'm glad you liked it!

I've added missing semicolon and additional author as you asked. 26955db
The core plugin is yours, I just made some refactoring and improvements :)

And where the building/linting scripts or tasks are located? I don't see them, neither documentation how to build the project.

**Comment by DataTables** [comment]
Awesome - thanks! This will be released alongside the next DataTables release.

The build scripts are in the DataTables/DataTablesSrc repo (scripts/make.sh) which I _really_ need to get around to fully documenting and publishing instructions for.

**Pull request merged**
