### PR TITLE
diacritics-neutralise filter and diacritics-neutralise sorting plug-in

### PR DESCRIPTION
**Pull request by davidkonrad**
Two suggestions:

* A type based filter for neutralising accented characters or letters with diacritical marks more exhaustive than accent-neutralise.js

* A sorting plug-in with the same purpose

regards,

### CODE REVIEW

**Comment by DataTables** [comment]
Very cool - thanks for this!

Are you happy for this to be included under the MIT license?

It might also be worth taking a look at my recent work on the Javascript I18n API integration with DataTables: https://www.datatables.net/blog/2017-02-28 . That will help with the sorting aspect but not the filtering (yet).

**Comment by davidkonrad** [comment]
>Are you happy for this to be included under the MIT license?

Yes of course.

Really interesting with window.Intl(), didnt' knew you have integrated that
:( Have never used it, but looks like it is the way to go. Seems to be
adopted heavily by all browsers (about time).  But it is a step more,
perhaps many developers will forget or overlook to set
$.fn.dataTable.ext.order.intl(lang). Maybe it could be integrated with the
language struct, like language: { intlLang : 'fr', ..}. or intlLang: {
'fr', options }, .. If intlLang is set,
$.fn.dataTable.ext.order.intl(intlLang) could be executed automatically. It
would not spoil backward compatibility (I believe) and users / developers
would only need to focus on one thing.

**Comment by davidkonrad** [comment]
>Are you happy for this to be included under the MIT license?

Yes of course.

Really interesting with `window.Intl()`, didnt' knew you have integrated that :( Have never used it, but looks like it is the way to go. Seems to be adopted heavily by all browsers (about time).  But it is a step more, perhaps many developers will forget or overlook to set `$.fn.dataTable.ext.order.intl(lang)`. Maybe it could be integrated with the `language` struct, like `language: { intlLang : 'fr', ..}` or `intlLang: {
'fr', options }, ..}`  If `intlLang` is set, `$.fn.dataTable.ext.order.intl(intlLang)` could be executed automatically. It would not spoil backward compatibility (I believe) and users / developers would only need to focus on one thing.

**Comment by DataTables** [comment]
With the next major version of DataTables I'm likely to include support for the I18n API directly into DataTables core. I need to work out a couple of issues with the filtering aspect, but that will also be included in the core as well.

**Pull request merged**
