### PR TITLE
Fix and expand Greek translation

### PR DESCRIPTION
**Pull request by larvanitis**
Added missing strings and corrected spelling

### CODE REVIEW

**Comment by DataTables** [comment]
Thank you. Are you happy for this to be released under the MIT license?

**Comment by DataTables** [comment]
Also, we should really keep "Abraam Ziogas"'s name, as well as adding your own, as he is the original author..

**Comment by larvanitis** [comment]
Yes, sorry for the name changed. We can remove mine if you want - it was placed there for internal reference.

I am ok with MIT license.

Do you want me to modify the pull request with "Abraam Ziogas"'s name?

**Comment by DataTables** [comment]
We should add your own as well as keeping the original I think since you've both contributed to it!

If you can update the PR, that would be great.

**Comment by larvanitis** [comment]
Done!

**Comment by DataTables** [comment]
Awesome - thanks.

**Pull request merged**
