### PR TITLE
Update Azerbaijan.lang

### PR DESCRIPTION
**Pull request by mahammad**
Azerbaijani equivalents of all variables are added

### CODE REVIEW

**Comment by DataTables** [comment]
Hi! Huge thanks for this, but could you make contributions to the translations at https://datatables.net/plug-ins/i18n as [noted in the readme](https://github.com/DataTables/Plugins#internationalisation).

**Comment by mahammad** [comment]
You are welcome, I will support as I find more time 🥰

**Comment by mahammad** [comment]
@DataTables All of done 👍🏻  😸

**Comment by DataTables** [comment]
Thank you - we'll need to port them over to https://datatables.net/plug-ins/i18n . If you get a chance to do so before we are able to do so, that would be very welcome. otherwise, we'll move them over and get them committed in.

**Comment by SandyDatatables** [comment]
Hi @mahammad ,

I've just copied these across into the contribution system as you can see [here](https://datatables.net/plug-ins/i18n/Azerbaijan.html).

Allan will get these committed into the repo soon. I'm going to close this issue now.

Thanks again for taking the time to contribute this translation!

**Pull request closed without merging**
