### PR TITLE
Update German.lang: add sDecimal

### PR DESCRIPTION
**Pull request by karyon**
That fixed some sorting in my project. Let me know if there was a specific reason why this wasn't added before.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for the PR. The reason it wasn't included originally is that this option didn't exist when the file was originally created.

I'm somewhat hesitant to include it now since it would introduce backwards compatibility issues. If you set the decimal character to be a comma, the dot that was used before will no longer sort numerically...

I'm not quite sure what the best thing to do is here to be honest. I think including it and having tables that previously numerically sorted with a dot change to no longer numerically sort would be the wrong action.

Possible with the next major update to DataTables that would be the time to make such a change.

**Comment by karyon** [comment]
although i'd like to see this merged of course, objectively you're probably right and shouldn't break backcompat in a minor release.

including it in a major release sounds safe, doesn't it? besides, not including such bugfixes at all is not really an option, right? :)

**Comment by karyon** [comment]
just don't forget it in the next release ;)

**Comment by DataTables** [comment]
It does rather beg the question: How many are using this translation file without adding the decimal option (i.e. leaving it as a dot by default). If the majority of your countrymen are using a dot for the decimal character, then this would introduce more "bugs" than it would resolve...

**Comment by karyon** [comment]
in germany, using a point as decimal separator isn't just unusual but plain wrong. a point can used for separating three digits, e.g. 1.000.000,0€ are a million euros. using a point as decimal separator will most likely cause confusion among non-technical people and i'd consider it a bug in any site's localization.

**Comment by DataTables** [comment]
Excellent - thanks for your feedback! The reason I asked was because this is the first time it has been mentioned that this option is missing, so I was wondering if others simply don't care, use it as it is, aren't aware of the decimal option, or prefer it the current way. I'm very wary of breaking existing installs!

**Comment by mkurz** [comment]
+1 for merging this. We just stumpled over this issue.
I agree with @karyon - I think this actually is a bug and should get fixed.

**Comment by SandyDatatables** [comment]
I can't pinpoint exactly where but at some point decimal was added as a language option and the decimal option has since been set for the German. The full JSON is avaliable [here](https://datatables.net/plug-ins/i18n/German.html). Because of this I am going to close this issue off.

I'll also mention that there is a [new system](https://datatables.net/plug-ins/i18n/) in place for contributing language translations rather than pull requests.

Thanks again for taking the time to contribute your translations.

**Pull request closed without merging**
