### PR TITLE
Update french.lang

### PR DESCRIPTION
**Pull request by schizophrene**
Old references deleted, correction of some fiw translation, reordered elements.
Also, the actual file is not JSON compliant.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this. However, the `select` entry probably should be retained. That's for the Select extension for DataTables.

**Comment by schizophrene** [comment]
Hi Allan,

Before validate pull request, I saw that this `select` entry is not present for a lot of translations (for these I've checked).
However, I saw that Finnish translation have it, also with `button` entry.

Tell me if both are needed, I will update my file.

**Comment by DataTables** [comment]
That looks good - thanks. Are you happy for this to be included under the MIT license?

**Comment by schizophrene** [comment]
For sure !

**Pull request merged**
