### PR TITLE
Add data renderer "anchor"

### PR DESCRIPTION
**Pull request by WinterSilence**
"anchor" renders the column data as HTML anchor.

This renderer more flexible than [hyperLink](https://datatables.net/plug-ins/dataRender/hyperLink):
- also supports phone numbers and emails
- can set inner text by `data`
- can customize tag attributes

### CODE REVIEW

**Comment by AllanJard** [comment]
Like it! Thanks for submitting this. Are you happy for it to be included and distributed under the MIT license?

**Comment by WinterSilence** [comment]
@AllanJard is redundant question, [repo contributers accept license](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants)

**Comment by WinterSilence** [comment]
@AllanJard offtop: renderer must return string or `HTMLAnchorElement`/`jQuery` object too allowed?

**Comment by AllanJard** [comment]
Currently a string.

**Comment by WinterSilence** [comment]
@AllanJard Are you happy for it to be included and distributed under the MIT license? ✔️

**Comment by WinterSilence** [comment]
@AllanJard we waiting something?

**Comment by AllanJard** [comment]
Nope - just me remembering to do it! Thanks for the PR!

**Pull request merged**
