### PR TITLE
Conditional Pagination Plugin

### PR DESCRIPTION
**Pull request by mjhasbach**
Added conditional pagination plugin as discussed [here](https://github.com/DataTables/DataTables/issues/511).

### CODE REVIEW

**Comment by DataTables** [comment]
Very nice - thanks! Let me review it when I get a chance and get back to you.

**Comment by DataTables** [comment]
Sorry for the delay - one or two little things from looking over the code:

1) `fadeIn()` and `fadeOut()` use display:none/block so the element could alter the layout of the page when it is removed. This might be a little jarring if the rest of the page suddenly shifts up. I wonder if animating the opacity might be better from this point of view?

2) I think the present of the `conditionalPagination` parameter should be enough to enable the plug-in, much like the other plug-ins. For example the user could use:

```
conditionalPagination: true

// or
conditionalPagination: {
  style: 'fade',
  speed: 400
}
```

3) DataTables 1.10 made some changes in the documented naming of parameter, paging for example is controlled by the parameter `paging` and `pagingType`, so I wonder if this might be better called `conditionalPaging` for consistency.

What do you think? Happy to pull it in and make these changes, or for you to update the PR - whichever you prefer.

**Comment by mjhasbach** [comment]
Thanks for the suggestions! Let me know what you think.

**Comment by DataTables** [comment]
Nice one - thanks! I suspect that the logic in the middle can probably be reduces a little bit with ternary operators, but that's a _very_ minor thing.

I like it a lot - thanks for contributing this!

**Comment by mjhasbach** [comment]
Thanks @DataTables!

**Comment by ltdeta** [comment]
the conditionalPaging plugin only triggert on ```init.dt```
```js
$(document).on('init.dt', function(e, dtSettings) {
```
i am using pagination-lngth so i changed it , because the visible rows changed but not pagination
```js
$(document).on('init.dt,length.dt', function(e, dtSettings) {
```
some other events could be related [datatable-events](http://www.datatables.net/reference/event/)
maybe the events are optional selectable

**Comment by DataTables** [comment]
@ltdeta - It is listening for DataTables initialisation and then applying its "constructor" which listens for a "draw' event. Whenever `length.dt` is triggered, `draw.dt` should also be. Also jQuery events ue a space a s separator, not a comma.

If the plug-in isn't working for you, please link to a test case showing the issue.

**Comment by ltdeta** [comment]
You are right, this makes no sense!
I prefer to take a closer look to see whats wrong

**Comment by pjfsilva** [comment]
this is a very useful plugin, why isn't it referenced on https://www.datatables.net/plug-ins/index page?

**Comment by DataTables** [comment]
I've not set the site up for the features plug-ins yet. Its on my ever expanding todo list :-)

**Pull request merged**
