### PR TITLE
Fix thousands separator in Slovak language file

### PR DESCRIPTION
**Pull request by freezy-sk**

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this. Wikipedia has Slovenia using a comma for the decimal, similar to most of the rest of Europe. Is there an official resource which says what Slovenia uses, or is the space your own preference?

**Comment by DataTables** [comment]
Forgot the wikipedia link: https://en.wikipedia.org/wiki/Decimal_separator#/media/File:DecimalSeparator.svg

**Comment by freezy-sk** [comment]
Hi @DataTables 
Slovak is not Slovenia, but Slovakia :)
Number format in Slovakia is like `1 000 000,00`. That's why I've changed thousands separator to space instead of comma.

**Comment by DataTables** [comment]
Sorry! Consider me an uneducated British oaf...! :-)

Is that a country-wide format, or something you prefer? Is there an government example? I'm just aware that if I change this here, it might mess around with other users who are already using it, so I want to be use that is it is the right thing to do - and as we've already seen, my local knowledge is rather lacking...

**Comment by freezy-sk** [comment]
@DataTables no problem ;)

I was looking for some "trusted" source as reference, but didn't found any in English.
We can use https://sk.wikipedia.org/wiki/Pomoc:Typografia#%C4%8C%C3%ADsla as reference, which summarizes few norms and rules.

Decimal point - decimal part of a number is separated by a comma (a punctuation mark)
Grouping digits - longer numbers are visually divided into groups of 3 digits with non breaking space between them
Examples
Wrong: 123.5; 1.000.000; 3000 0000
Right: 123,5; 1 000 000; 30 000 000

**Comment by DataTables** [comment]
That works for me. Thanks for your input and helping to make DataTables better :-)

**Pull request merged**
