### PR TITLE
Copied i18n lang files to a new folder with its respectively country's ISOCODE

### PR DESCRIPTION
**Pull request by zicoNextt**
Once the languages files were named based on its language name, and I needed to be based on the country's ISOCODE, I copied all of them into this new ISO folder and replaced the names with its respectively country's ISOCODE. Hopefully, this may be usefull for more users.

### CODE REVIEW

**Comment by DataTables** [comment]
Hi,

Thanks for this. I'm not going to pull it in at the moment though as I know there are a number of other build systems that rely on the current structure. Ultimately I think this is a good idea and perhaps it should be done in parallel. I know I need to do some work on the i18n support so I will look at this when I do that.

**Comment by zicoNextt** [comment]
Ok, thanks for your quick response! =D

**Comment by althaus** [comment]
@DataTables It would be awesome, if you could look into removing the comments in each file. They make the JSON files invalid and therefore cannot be used directly. You shouldn't do it, but I simply added the complete plugins package through bower for the dev process/environment where no minification runs (triggered by Assetic from the Symfony PHP world).

**Comment by zicoNextt** [comment]
I've seen this after I did the pull request, so I removed the comments, but
my final solution was not to use json, once I was having a lot of bugs when
loading the language thought ajax in combination with other plugins.

My final solution was tu use a js file which set a language variable that i
called "dataTableLang", I got the idea from this datepicker plugin I am
using (https://github.com/eternicode/bootstrap-datepicker/). You can see
how it works in here:
http://bootstrap-datepicker.readthedocs.org/en/latest/i18n.html

So, based on datepicker, that is how I set the datatables language on my
application:

On server side:
<c:if test="${currentLanguage.isocode != 'en'}">
<script type="text/javascript"
src="${themeResourcePath}/js/datepicker/locales/bootstrap-datepicker.${currentLanguage.isocode}.js"></script>
<script type="text/javascript"
src="${themeResourcePath}/js/dataTables/locales/${currentLanguage.isocode}.js"></script>
</c:if>


On my datatables js file, where I initialize the datatable (the
".xtt-datatable" elemnts must have the datables plugin):

$('.xtt-datatable').each(function(){
 .....
 var options = {"paginate": false, "order": [], "info": false,
"lengthChange":false};
 .....
 if(typeof dataTableLang !== typeof undefined){
  options['language'] = dataTableLang;
 }
 .....
}

I attached the js files I migrated from the .lang format.

Hope I made myself usefull.

Any question I'd be glad to help


Att,
Zico Montibeller

**Comment by zicoNextt** [comment]
ops, I forgot to mention the final line where I call the dataTable function:

$('.xtt-datatable').each(function(){
 .....
 var options = {"paginate": false, "order": [], "info": false,
"lengthChange":false};
 .....
 if(typeof dataTableLang !== typeof undefined){
  options['language'] = dataTableLang;
 }
 .....
 $(this).dataTable(options);

}

**Pull request closed without merging**
