### PR TITLE
Updating natural-time-delta plugin

### PR DESCRIPTION
**Pull request by saveshodhan**
Added support for decades, years, months, milliseconds and microseconds

### CODE REVIEW

**Comment by saveshodhan** [comment]
just a small doubt here - i have simply done multiplication by **30** days for months. i guess this should not get affected by the fact that months are not always of 30 days?

**Comment by DataTables** [comment]
In this particular case, it probably is okay since you aren't specifying which month something is in - rather the text would simply state "x month(s)". For that reason leap years probably aren't important either.

Happy with the MIT license for this one?

One other point - it might be worth allowing for singular as well as plurals - e.g. "1 week" v "1 weeks".

**Comment by saveshodhan** [comment]
> In this particular case, it probably is okay since you aren't specifying which month something is in - rather the text would simply state "x month(s)". For that reason leap years probably aren't important either.

that seems okay

> Happy with the MIT license for this one?

yup!

> One other point - it might be worth allowing for singular as well as plurals - e.g. "1 week" v "1 weeks".

The `s?` in `weeks?` etc. in the regex takes care of that. Here's a [JSFiddle](https://jsfiddle.net/r6wzr1eb/4/)

**Comment by saveshodhan** [comment]
I guess i forgot to update the doc.. what should i do? Is it okay if i make another pull request affer this one is done?

**Comment by saveshodhan** [comment]
Nevermind, i pushed another commit.. still learning.. :P

**Comment by saveshodhan** [comment]
There's a typo in the commit message `Updating natural-time-detal plugin`..

**Comment by DataTables** [comment]
Oops - sorry. I misread the regex - yes it does indeed handle singles and plurals.

Thanks for the updates!

**Pull request merged**
