### PR TITLE
Added pagination plug-ins

### PR DESCRIPTION
**Pull request by mpryvkin**
Added two pagination plugins "Full Numbers - No Ellipses" and "Simple Numbers - No Ellipses". 

See [example](http://www.gyrocode.com/articles/jquery-datatables-pagination-without-ellipses) for demonstration.

### CODE REVIEW

**Comment by DataTables** [comment]
Cool - thanks! I'll try to find some time to review and pull it in soon. When I get to it, are you happy for this to be included under the MIT license?

**Comment by mpryvkin** [comment]
Sure, MIT license is OK. Should I include reference to MIT license in the plug-in code or is it OK as it is?

**Comment by DataTables** [comment]
Everything under this repo is MIT so fine as is :-)

**Comment by jeff1234** [comment]
Does it work?

**Comment by mpryvkin** [comment]
Yes, see [this example](http://www.gyrocode.com/articles/jquery-datatables-pagination-without-ellipses) for demonstration.

**Comment by mpryvkin** [comment]
Any progress on this?

**Comment by DataTables** [comment]
Thanks for the reminder. It had slipped my mind with everything else going on.

Just to confirm - the only difference between this and the built in paging options is that it doesn't show an ellipsis? If that is the case, would it not be easier to simply use `span.ellipsis { display: none; }`?

**Comment by mpryvkin** [comment]
Not really, see the examples in my article [jQuery DataTables – Pagination without ellipses](http://www.gyrocode.com/articles/jquery-datatables-pagination-without-ellipses/). 

With ellipses pagination appears as:

`First` `Prev` `1` `2` `3` `4` `5` `...` `18` `Next` `Last`

`First` `Prev` `1` `...` `6` `7` `8` `...` `18` `Next` `Last`

Without ellipses pagination appears as:

`First` `Prev` `1` `2` `3` `4` `5` `6` `7` `Next` `Last`

`First` `Prev` `4` `5` `6` `7` `8` `9` `10` `Next` `Last`

**Comment by DataTables** [comment]
Got it! Thanks :-)

**Comment by mpryvkin** [comment]
Should I write description similar to http://datatables.net/plug-ins/pagination/ellipses or you do it on your own discretion?

**Comment by DataTables** [comment]
A description would be welcome.

**Comment by mpryvkin** [comment]
# No Ellipses #
Hides ellipses in the pagination control

- Author: [Michael Ryvkin](http://www.gyrocode.com/articles/jquery-datatables-pagination-without-ellipses/)

## Description ##

This plug-in works similar to default pagination options `full_numbers` and `simple_numbers`, except that it hides ellipses and replaces them with page numbers instead. 

It adds two new pagination options `full_numbers_no_ellipses` and `simple_numbers_no_ellipses`.

* `simple_numbers_no_ellipses` - 'Previous' and 'Next' buttons, plus page numbers without ellipses
* `full_numbers_no_ellipses` - 'First', 'Previous', 'Next' and 'Last' buttons, plus page numbers without ellipses

## Example ##

    $('#example').DataTable( {
        'pagingType': 'simple_numbers_no_ellipses'
    } );

## Demo ##

  See [this example](http://www.gyrocode.com/articles/jquery-datatables-pagination-without-ellipses/) for demonstration.

**Pull request merged**
