### PR TITLE
Add russian translation for Editor

### PR DESCRIPTION
**Pull request by ashl1**
Add russian translation for Editor

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! Editor's i18n options are currently separate from DataTables' own, so this field with need to either be loaded twice, or once with a custom Ajax call and passed into the two libraries.

I'm not sure what the best way of handling this is at the moment - let me think about it can get back to you.

**Comment by ashl1** [comment]
Lets thinking about it. I know three ways:
* DT
* Editor
* DT + Editor
For first and second cases we should require the possibility to use/download the language file.
For the last I will prefer that Editor use the DT language. I think the better is to have one shared language file. It can apply now for both DT and Editor in any provided cases.
As I prefer to use single js and don't use AJAX if it's possible to not use it to decrease the queries and client lag, I embed the local into one js file while building.

**Comment by DataTables** [comment]
The [`i18n()` method](//datatables.net/reference/api/i18n()) in the newer DataTables versions presents options - but generally Editor needs the language information before DataTables has been initialised, so that might not work.

Possibly DataTables needs to present a static function with a static cache for loading language files.

**Comment by SandyDatatables** [comment]
Since the last comments on this PR editor's language options have been included in the i18n object. Translations have also been provided for editor options in Russian - the full translation can be [found here](https://datatables.net/plug-ins/i18n/Russian.html).

Because of these reasons, I am going to close this PR now.

Thanks again for taking the time to contribute!

**Pull request closed without merging**
