### PR TITLE
Fix file-size plugin with string containing spaces

### PR DESCRIPTION
**Pull request by Silex**
**DONT MERGE THIS YET**

Fix for #229 

Still needs to be actually tested :)

### CODE REVIEW

**Comment by Silex** [comment]
@DataTables: alright, you can merge this

**Comment by DataTables** [comment]
Nice one - thank you for this. Are you happy for it to be released under the MIT license?

**Comment by Silex** [comment]
@DataTables: yep it's fine.

**Comment by DataTables** [comment]
Ace - thanks :-)

**Pull request merged**
