### PR TITLE
Fix one problem and add one additional parameter.

### PR DESCRIPTION
**Pull request by AlexDEVpro**
I ran into two problems with pageResize plugin when using "angular-datatables v0.5.x" DataTables.net wrapper for AngularJS. It has a specific layout, so I made these commits inside the fork.
I want to propose these changes, in case you consider it advisable to add them to the original repository.

### CODE REVIEW

**Comment by DataTables** [comment]
Hi - thanks for this!

With the first commit - DataTables doesn't require a footer, but it does require a header. How did you get it to work without a header? Having said that, I'm absolutely fine with that bit.

The second commit (652507a) - what would the manual delta be used for?

Last question - are you happy for this to be included under the MIT license?

**Comment by AlexDEVpro** [comment]
Hi!

> DataTables doesn't require a footer, but it does require a header.
Ok, it turns out that it's enough to leave a check for the absence of a footer.
> The second commit (652507a) - what would the manual delta be used for?
I use the wrapper for DataTables - "angular-datatables v0.5.x".
I had to add delta so that the table fit in the container and to avoid scrolling.
In the HTML layout provided and added to result HTML by the wrapper, there is an element above the header. This element contains the search input. In addition, the footer is also there, but table.footer() returns null (but this is probably a bug in the wrapper).
Thus, delta is used to take into account the heights of elements whose HTML markup is not directly controlled, if such exist.
I understand that this is a rather specific modification, but it may be needed in other cases. You know better.

> Last question - are you happy for this to be included under the MIT license?
Yes, of course.

**Comment by DataTables** [comment]
Got it - thanks! I've merged it in now. I might change the delta's name a little (padding or offset would be more in keeping with the DataTables naming conventions), but I can see that its a useful feature.

**Comment by AlexDEVpro** [comment]
Ok, thank you!

**Pull request merged**
