### PR TITLE
Added russian translation for Select plugin

### PR DESCRIPTION
**Pull request by MarkKhromov**

### CODE REVIEW

**Comment by DataTables** [comment]
Thank you! Are you happy for this to be included under the MIT license

Also, its not actually valid JSON like that - missing a leading comma. But I can fix that unless you want to update the PR?

**Comment by MarkKhromov** [comment]
> Thank you! Are you happy for this to be included under the MIT license
> 
> Also, its not actually valid JSON like that - missing a leading comma. But I can fix that unless you want to update the PR?

Oh, it's my bad, sorry! Thanks! Fixed! <3

**Comment by DataTables** [comment]
Thank you!

Are you happy with the MIT license?

**Comment by MarkKhromov** [comment]
> Thank you!
> 
> Are you happy with the MIT license?

Yes, so much!

**Comment by DataTables** [comment]
Thank you! :-)

**Pull request merged**
