### PR TITLE
Add some more ja translations

### PR DESCRIPTION
**Pull request by asavageiv**

### CODE REVIEW

**Comment by asavageiv** [comment]
I did not see how to edit this using the management system on the website, so I thought the PR was appropriate. If I should do something differently please let me know!

**Comment by SandyDatatables** [comment]
Hi @asavageiv ,

If you go to [this page](https://datatables.net/plug-ins/i18n/) then there should be a contribute button on the right hand side.

image

You have to be logged in to make contributions though so make sure you have an account and are logged in!

If you could make your changes there that would be greatly appreciated.

Thanks,
Sandy

**Comment by asavageiv** [comment]
Got it. I submit my changes there.

**Comment by SandyDatatables** [comment]
Perfect - thank you!

Just to confirm the commit has been made in [this commit](https://github.com/DataTables/Plugins/commit/201e325c2db626769ae868e23a920d4108662224).

Thanks,
Sandy

**Pull request closed without merging**
