### PR TITLE
Fixed issue - Datatable is displaying old value when user clicks next…

### PR DESCRIPTION
**Pull request by priyankaa-patil**
Startindex was always zero even after clicking on any page number.This PR has fix for that.
Please have a look and let me know if any changes required

### CODE REVIEW

**Comment by DataTables** [comment]
Thank you for this. Are you happy for this to be included under the MIT license?

**Comment by priyankaa-patil** [comment]
Hi Allan,

I do not have any problem.
I would be happy to do that.

Regards,
Priyanka

**Comment by DataTables** [comment]
Thanks for your contribution!

**Comment by priyankaa-patil** [comment]
Thank you for reviewing and merging to master.
I wil continue to contribute further.

**Pull request merged**
