### PR TITLE
Added support for search, sorting, numbers, localization

### PR DESCRIPTION
**Pull request by mpryvkin**
See demo at http://www.gyrocode.com/articles/jquery-datatables-alphabetical-search/

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! I'll try to make some time later this week to review it :-)

**Comment by DataTables** [comment]
Highlevel points:

1. I don't understand the sorting aspect. This plug-in is a filter, so I don't see either why, or where, sorting would come into play?
2. To my mind a plug-in such as this should provide one feature only - in this case filtering using the alphabet input. Row grouping show not be provided by this plug-in. In the medium term I plan to release a new row grouping extension for DataTables which would conflict with this for example.
3. White space has been changed from tabs to 3 spaces. The original formatting should be preserved please :-).
4. I think the code size could be compressed and made more readable by storing sub-objects into variables for local use. For example properties of `settings.alphabetSearch` are used a number of times in the constructor - the code would be faster, smaller and more readable if it was stored in a `alphaSettings` variable or similar.

**Comment by mpryvkin** [comment]
Thanks for your feedback.

Sorry for replacing tabs with spaces, I noticed that only after committing the code. It has been fixed.

You have a [special category](https://datatables.net/manual/plug-ins/) (feature) for a reason for such plug-ins among searching, ordering, etc. This means to me that these plugins could provide more than just searching, ordering. I think row grouping is necessary for this kind of feature (see https://news.google.com/newspapers, for example)

Also you have [some extensions conflicting with others](https://datatables.net/download/compatibility#Feature-compatibility), so it could be up to the user to decide which ones to use.

So ordering is just another functionality provided by this feature plug-in, it sorts rows within its own row group.

Regarding `settings.alphabetSearch`, it has been implemented like that in the original code so that settings could be accessed in search and order plug-ins. I'm not sure what you mean how using  local variable could be faster.

I really don't mean to introduce something that you don't want in the code base. If that is so, please don't hesitate to let me know. I will just host this code in a separate repository.

**Comment by DataTables** [comment]
Thanks for your reply. I appreciate your thoughts on this. I think, for the moment I would prefer that this plug-in remain just for filtering and additional options can be configured as people need.

I won't take this PR as it is, but if I get a chance I'll bring in the i18n and numbers aspect, as I think those are really useful additions.

**Comment by mpryvkin** [comment]
I understand. I think I will create a separate repository to host this version of the plug-in retaining all the copyright of course.

**Comment by mpryvkin** [comment]
For the sake of reference, added a new repository at https://github.com/gyrocode/jquery-datatables-alphabetSearch

**Comment by DataTables** [comment]
Awesome - thanks!

**Pull request closed without merging**
