### PR TITLE
Update bn.json

### PR DESCRIPTION
**Pull request by csesumonpro**

### CODE REVIEW

**Comment by SandyDatatables** [comment]
Hi @csesumonpro  ,

As stated in the readme, please can you submit your changes at this page https://datatables.net/plug-ins/i18n/

Thanks,
Sandy

**Comment by csesumonpro** [comment]
> 
HI @SandyDatatables ,
I have already updated [datatables.net plugin bn.json file.](https://datatables.net/plug-ins/i18n/) Please check it. 

Thanks,
Sumon

**Comment by SandyDatatables** [comment]
Hi @csesumonpro ,

There have been a lot of Bangla translations made on the page that I linked above yesterday - I'm assuming this was you? Thank you!

I've approved them there, Allan will commit them in when he next gets a chance and update you here.

Thanks again,
Sandy

**Comment by csesumonpro** [comment]
Hi, @SandyDatatables 
Thanks for your update.

**Comment by AllanJard** [comment]
[Here we go](https://github.com/DataTables/Plugins/commit/1018be0fb19b499ab3022b5fed0d9ed88649ad2c). Many thanks for your contribution to DataTables! We'll be doing a release early next week, and it will be included in that.

**Comment by csesumonpro** [comment]
Hi, @AllanJard 

Thanks for your update
Sumon

**Comment by SandyDatatables** [comment]
Hi @csesumonpro ,

I'm going to close this pull request now that they have been commited in elsewhere.

Thanks again for your contribution!

**Pull request closed without merging**
