### PR TITLE
Create sliding-child.js

### PR DESCRIPTION
**Pull request by data-handler**
I have never made a pull request on github before, so I plead ignorance if I am doing anything incorrectly.

### CODE REVIEW

**Comment by DataTables** [comment]
Hi! Sorry for the delay in replying here.

Was this closed intentionally? Might you be willing to submit another PR with the plug-in? It looks like it would be really useful.

**Comment by data-handler** [comment]
Hi Allan, no worries. I removed it because I thought there was no interest in it. I should learn to be more more patient. You must be immensely busy!

**Comment by DataTables** [comment]
Yeah sorry - I'm not managing to keep up with things at the moment! I'll take a look over your code as soon as possible before pulling it in.

Are you happy for this to be included under the MIT license?

**Comment by data-handler** [comment]
Yes, that's fine. Thanks

**Comment by data-handler** [comment]
Hi again. Just wondering if you've had a chance to review this code yet? Would be great to get some feedback

**Comment by DataTables** [comment]
Frustratingly no, not yet, sorry. I'm been a little overwhelmed with support requests at the moment. I have got this in my inbox to look at so I won't forget though!

**Comment by data-handler** [comment]
Sorry, I don't mean to pester. Thanks

**Comment by DataTables** [comment]
I'm finally here - sorry for the massive delay.

I think this looks excellent - thanks so much!

The only thing I would suggest changing is the copyright header - it should be copyright to yourself :).

**Comment by data-handler** [comment]
Absolutely no need to apologise. I feel happy to have contributed.

**Pull request merged**
