### PR TITLE
Pashto translation from Muhammad Nasir Rahimi

### PR DESCRIPTION
**Pull request by mbrig-co**
Add Pashto translation to the documentation website internationalization plugins list.

### CODE REVIEW

**Comment by DataTables** [comment]
We did this yesterday with #284 did we not?

**Comment by mbrig-co** [comment]
But it is not available in this translations list: https://datatables.net/plug-ins/i18n/
Is it available there?

**Comment by DataTables** [comment]
No not yet. It will be when I next release the plug-ins, which will be alongside the next version of DataTables. I'm not sure yet when that will be.

The plug-ins shown on the site are tied to the releases.

Going to close this as the required file is in the repo already.

**Comment by mbrig-co** [comment]
Okay I got it, thanks.

**Pull request closed without merging**
