### PR TITLE
any-number & nepali-numbers sorting plugins

### PR DESCRIPTION
**Pull request by davidkonrad**
Two small sorting plugins. perhaps they are useful. Regards :)

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks for this! I'll try to review them in the next few days.

**Comment by DataTables** [comment]
This has taken me _way_ too long to get back to you on this - sorry!!

They look great! Are you happy for these to be included under the MIT license?

**Comment by davidkonrad** [comment]
Hey Allan Jardine,

Have forgotten all about it myself :) Yes! As far as I recall it was a pull
request on github.com/DataTables/Plugins. ..? If you do so, I have a more
effective accent filter / sort I would like to PR also (afterwards, think I
need to get my own repository in sync first).

regards,

**Comment by DataTables** [comment]
Yes indeed - https://github.com/DataTables/Plugins/pull/248 is the PR url.

A more effective accent filter / sort sounds really interesting - yes please!

**Pull request merged**
