### PR TITLE
Sorting empty values

### PR DESCRIPTION
**Pull request by timothystewart6**
Sorts cells with empty values by placing them after cells with values. This helps when if you have column that may or may not have values allowing items with values to appear first when sorting ascending. This was written to help with sorting items that were ranked, where items without a rank number were considered lower in rank.

### CODE REVIEW

**Comment by DataTables** [comment]
This completely slipped by me - sorry about that!

Are you happy for this to be included under the MIT license?

**Comment by timothystewart6** [comment]
Yes

**Comment by DataTables** [comment]
There is actually [this plug-in](https://github.com/DataTables/Plugins/blob/master/sorting/absolute.js) which I think basically does the same job, but has a little more flexibility. It wasn't available at the time of the original PR, and I guess I forgot about it in my comment above. I'm really sorry that this slipped past me at the time! Given that they basically do the same thing, rather than including both and potentially confusing folks, it would probably be an idea to just use one.

Does that seem okay?

**Comment by timothystewart6** [comment]
Sure, sounds good to me!  I forgot about this one too.  No worries.

**Pull request closed without merging**
