### PR TITLE
Update Chinese-traditional.lang

### PR DESCRIPTION
**Pull request by jiunjiun**

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks - but this PR is still converting the camelCase notation to Hungarian notation like #278 was. Could you leave it as camelCase notation please.

**Comment by Changhsun-Wu** [comment]
@DataTables 
I don't understand either, could you please explain more specific about the wrong notation part?
I think as long as to be the same format as others would be fine.
Like English.lang : [https://github.com/DataTables/Plugins/blob/master/i18n/English.lang](
https://github.com/DataTables/Plugins/blob/master/i18n/English.lang)

**Comment by DataTables** [comment]
If you look at the [diff](https://github.com/DataTables/Plugins/pull/279/commits/a4c0b2808a905be2c04a639095f5c254ee2666dd) you'll be able to see that every line of code has changed, including the parameter names - for example `processing` has become `sProcessing` (which is the legacy style).

**Comment by jiunjiun** [comment]
I refered to two examples as follows:
[https://datatables.net/examples/basic_init/language.html](https://datatables.net/examples/basic_init/language.html)
[https://datatables.net/plug-ins/i18n/](https://datatables.net/plug-ins/i18n/)

and write two samples:
[https://jsfiddle.net/0hkh65w2/](https://jsfiddle.net/0hkh65w2/) which can works (Japanese )
[https://jsfiddle.net/gk5he0x0/](https://jsfiddle.net/gk5he0x0/)   which can’t works (Chinese-traditional)
so I guess the problem is from the language url in Chinese-traditional one,
What steps should I take to correct this problem?

**Comment by DataTables** [comment]
Thanks for the links. jQuery is telling me that it is failing to parse the CDN Chinese traditional files:

> SyntaxError: Unexpected token   in JSON at position 18(…)

However, JSONLint.com tells me that it is valid JSON. I can currently only guess that there is some kind of character set issue, but I don't know what!

If you save the file locally rather than using it on the CDN does that work?

**Comment by s1awa** [comment]
@Changhsun-Wu The notation you use is legacy (old). The current notation is the newest.

The https://github.com/DataTables/Plugins/blob/master/i18n/English.lang is outdated! Don't use it as reference.

**Comment by DataTables** [comment]
Either form will actually work and I'll take a PR with either at the moment. With the next major update only the newer camelCase form will be accepted and I'll update all plug-ins to use that form at that time.

**Comment by s1awa** [comment]
@DataTables This PR only converts camelCase back to legacy.

**Comment by SandyDatatables** [comment]
There is now a [new system](https://datatables.net/plug-ins/i18n/) on the website for contributing translations, which should remove the casing issues discussed here.

All of the translations in the original request have now been provided one way or another, so I am going to close this PR. 

Thanks for taking the time to contribute your translations.

**Pull request closed without merging**
