### PR TITLE
Added simple incremental bootsrap pagination

### PR DESCRIPTION
**Pull request by JocaPC**
New type of pagination called simple/incremental pagination. It starts
as simple pagination, shown only prev/next buttons. When user advances
trough the pages using next button, this pagination remembers the last
page that is reached and generates page numbers up to the last known
page.

### CODE REVIEW

**Comment by DataTables** [comment]
I like this a lot - thanks for the PR!

Are you happy for this to be included under the MIT license?

**Comment by JocaPC** [comment]
Yes, sure. It can be MIT licence.

Thanks,
Jovan

**Comment by jovanpop-msft** [comment]
Hi, any news regarding this plugin? Are you plan to merge the PR?

**Comment by DataTables** [comment]
Sorry - it completely slipped my mind.

The good news is that improved paging plug-ins are coming to the next version of DataTables which will make it massively easier to write them.

**Pull request merged**
