### PR TITLE
Convert PT-BR terms into PT-PT

### PR DESCRIPTION
**Pull request by fabiofdsantos**
Apply changes considering PT-PT.

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks! Are you happy for this to be included under the MIT license?

**Comment by fabiofdsantos** [comment]
@DataTables, yes!

**Comment by DataTables** [comment]
Did you intentionally close this?

**Comment by fabiofdsantos** [comment]
@DataTable,
Sry, i've closed the pull request by mistake.

**Comment by DataTables** [comment]
No problem - its all too easy to do in Github! Thanks again for your PR :-)

**Pull request merged**
