### PR TITLE
Add bower support

### PR DESCRIPTION
**Pull request by dennisahlin**
I can only do this part, you have to do the rest in [this guide](http://bower.io/docs/creating-packages/#register) as well, to get full bower support.

### CODE REVIEW

**Comment by andythorne** [comment]
+1 for this!

**Comment by zargyle** [comment]
+1 please add

**Comment by riccardopietropala** [comment]
+1 for this!

**Comment by brunowego** [comment]
+1

**Comment by DataTables** [comment]
Bower package is now finally registered as `datatables.net-plugins`. See also #154.

**Pull request closed without merging**
